# Generated by Django 5.2.7 on 2025-12-07 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarefa_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criadaem'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
