# Generated by Django 5.2.7 on 2025-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tarefa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
    ]
