# Generated by Django 5.2.7 on 2025-12-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tarefa_deletada_tarefa_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='deletada',
        ),
    ]
