# Generated by Django 5.2.7 on 2025-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_tarefa_deletada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
